import {
  Supplier,
  Employee,
  Material,
  PR,
  PO,
  GR,
  Invoice,
  FraudAlert,
} from './types';
import { subMonths, subDays, format } from 'date-fns';

// Helper to generate dates
export const randomDate = (daysAgo: number) => {
  return format(subDays(new Date(), daysAgo), 'yyyy-MM-dd');
};

// Suppliers
export const mockSuppliers: Supplier[] = [
  {
    id: 'SUP-001',
    name: 'Astra Metals Pvt. Ltd.',
    country: 'India',
    city: 'Mumbai',
    category: 'Raw Material',
    avgLeadTimeDays: 45,
    onTimeDeliveryRate: 0.65,
    riskScore: 0.85,
  },
  {
    id: 'SUP-002',
    name: 'GlobalChem Logistics BV',
    country: 'Netherlands',
    city: 'Rotterdam',
    category: 'Logistics',
    avgLeadTimeDays: 30,
    onTimeDeliveryRate: 0.92,
    riskScore: 0.25,
  },
  {
    id: 'SUP-003',
    name: 'Pacific Packaging Solutions',
    country: 'China',
    city: 'Shanghai',
    category: 'Packaging',
    avgLeadTimeDays: 60,
    onTimeDeliveryRate: 0.55,
    riskScore: 0.90,
  },
  {
    id: 'SUP-004',
    name: 'TechServ Consulting Inc.',
    country: 'USA',
    city: 'San Francisco',
    category: 'Services',
    avgLeadTimeDays: 15,
    onTimeDeliveryRate: 0.95,
    riskScore: 0.15,
  },
  {
    id: 'SUP-005',
    name: 'Eastern Steel Works',
    country: 'India',
    city: 'Delhi',
    category: 'Raw Material',
    avgLeadTimeDays: 50,
    onTimeDeliveryRate: 0.70,
    riskScore: 0.75,
  },
  {
    id: 'SUP-006',
    name: 'Nordic Materials AB',
    country: 'Sweden',
    city: 'Stockholm',
    category: 'Raw Material',
    avgLeadTimeDays: 35,
    onTimeDeliveryRate: 0.88,
    riskScore: 0.30,
  },
  {
    id: 'SUP-007',
    name: 'Continental Services GmbH',
    country: 'Germany',
    city: 'Berlin',
    category: 'Services',
    avgLeadTimeDays: 20,
    onTimeDeliveryRate: 0.90,
    riskScore: 0.20,
  },
  {
    id: 'SUP-008',
    name: 'Ocean Freight Co.',
    country: 'Singapore',
    city: 'Singapore',
    category: 'Logistics',
    avgLeadTimeDays: 25,
    onTimeDeliveryRate: 0.85,
    riskScore: 0.40,
  },
  {
    id: 'SUP-009',
    name: 'Metro Packaging Industries',
    country: 'India',
    city: 'Bangalore',
    category: 'Packaging',
    avgLeadTimeDays: 40,
    onTimeDeliveryRate: 0.60,
    riskScore: 0.80,
  },
  {
    id: 'SUP-010',
    name: 'Advanced Materials Corp',
    country: 'USA',
    city: 'Chicago',
    category: 'Raw Material',
    avgLeadTimeDays: 28,
    onTimeDeliveryRate: 0.93,
    riskScore: 0.25,
  },
  {
    id: 'SUP-011',
    name: 'Rapid Logistics Ltd.',
    country: 'UK',
    city: 'London',
    category: 'Logistics',
    avgLeadTimeDays: 22,
    onTimeDeliveryRate: 0.87,
    riskScore: 0.35,
  },
  {
    id: 'SUP-012',
    name: 'Prime Services Group',
    country: 'India',
    city: 'Pune',
    category: 'Services',
    avgLeadTimeDays: 18,
    onTimeDeliveryRate: 0.75,
    riskScore: 0.60,
  },
];

// Employees
export const mockEmployees: Employee[] = [
  {
    id: 'EMP-001',
    name: 'Rohan Mehta',
    department: 'Procurement',
    role: 'Procurement Manager',
  },
  {
    id: 'EMP-002',
    name: 'Priya Sharma',
    department: 'Operations',
    role: 'Operations Manager',
  },
  {
    id: 'EMP-003',
    name: 'Amit Patel',
    department: 'Procurement',
    role: 'Senior Buyer',
  },
  {
    id: 'EMP-004',
    name: 'Sneha Reddy',
    department: 'Finance',
    role: 'Finance Manager',
  },
  {
    id: 'EMP-005',
    name: 'Vikram Singh',
    department: 'Procurement',
    role: 'Buyer',
  },
  {
    id: 'EMP-006',
    name: 'Anjali Desai',
    department: 'Operations',
    role: 'Operations Coordinator',
  },
  {
    id: 'EMP-007',
    name: 'Rajesh Kumar',
    department: 'Procurement',
    role: 'Procurement Manager',
  },
  {
    id: 'EMP-008',
    name: 'Meera Nair',
    department: 'Finance',
    role: 'Accounts Payable',
  },
  {
    id: 'EMP-009',
    name: 'Karan Malhotra',
    department: 'Procurement',
    role: 'Senior Buyer',
  },
  {
    id: 'EMP-010',
    name: 'Divya Iyer',
    department: 'Operations',
    role: 'Warehouse Manager',
  },
];

// Materials
export const mockMaterials: Material[] = [
  {
    id: 'MAT-001',
    code: 'STEEL-101',
    description: 'Carbon Steel Sheets',
    category: 'Raw Material',
  },
  {
    id: 'MAT-002',
    code: 'CHEM-205',
    description: 'Industrial Solvents',
    category: 'Raw Material',
  },
  {
    id: 'MAT-003',
    code: 'PKG-301',
    description: 'Corrugated Boxes',
    category: 'Packaging',
  },
  {
    id: 'MAT-004',
    code: 'SVC-401',
    description: 'Consulting Services',
    category: 'Services',
  },
  {
    id: 'MAT-005',
    code: 'LOG-501',
    description: 'Freight Services',
    category: 'Logistics',
  },
  {
    id: 'MAT-006',
    code: 'STEEL-102',
    description: 'Stainless Steel Rods',
    category: 'Raw Material',
  },
  {
    id: 'MAT-007',
    code: 'CHEM-206',
    description: 'Adhesive Compounds',
    category: 'Raw Material',
  },
  {
    id: 'MAT-008',
    code: 'PKG-302',
    description: 'Plastic Containers',
    category: 'Packaging',
  },
  {
    id: 'MAT-009',
    code: 'SVC-402',
    description: 'IT Support Services',
    category: 'Services',
  },
  {
    id: 'MAT-010',
    code: 'LOG-502',
    description: 'Warehouse Services',
    category: 'Logistics',
  },
  {
    id: 'MAT-011',
    code: 'STEEL-103',
    description: 'Aluminum Sheets',
    category: 'Raw Material',
  },
  {
    id: 'MAT-012',
    code: 'CHEM-207',
    description: 'Lubricants',
    category: 'Raw Material',
  },
  {
    id: 'MAT-013',
    code: 'PKG-303',
    description: 'Bubble Wrap',
    category: 'Packaging',
  },
  {
    id: 'MAT-014',
    code: 'SVC-403',
    description: 'Maintenance Services',
    category: 'Services',
  },
  {
    id: 'MAT-015',
    code: 'LOG-503',
    description: 'Express Delivery',
    category: 'Logistics',
  },
];

// Generate PRs
export const mockPRs: PR[] = [
  {
    id: 'PR-001',
    number: 'PR-2024-0001',
    requester: mockEmployees[0],
    department: 'Procurement',
    material: mockMaterials[0],
    quantity: 500,
    estimatedUnitPrice: 125.5,
    createdAt: randomDate(120),
    status: 'PO Created',
    supplierShortlist: [mockSuppliers[0], mockSuppliers[4]],
    riskScore: 0.75,
  },
  {
    id: 'PR-002',
    number: 'PR-2024-0002',
    requester: mockEmployees[0],
    department: 'Procurement',
    material: mockMaterials[1],
    quantity: 200,
    estimatedUnitPrice: 85.0,
    createdAt: randomDate(110),
    status: 'PO Created',
    supplierShortlist: [mockSuppliers[2]],
    riskScore: 0.90,
  },
  {
    id: 'PR-003',
    number: 'PR-2024-0003',
    requester: mockEmployees[2],
    department: 'Procurement',
    material: mockMaterials[2],
    quantity: 1000,
    estimatedUnitPrice: 12.5,
    createdAt: randomDate(100),
    status: 'PO Created',
    supplierShortlist: [mockSuppliers[8]],
    riskScore: 0.80,
  },
  {
    id: 'PR-004',
    number: 'PR-2024-0004',
    requester: mockEmployees[1],
    department: 'Operations',
    material: mockMaterials[3],
    quantity: 1,
    estimatedUnitPrice: 50000,
    createdAt: randomDate(90),
    status: 'PO Created',
    supplierShortlist: [mockSuppliers[3]],
    riskScore: 0.15,
  },
  {
    id: 'PR-005',
    number: 'PR-2024-0005',
    requester: mockEmployees[0],
    department: 'Procurement',
    material: mockMaterials[0],
    quantity: 300,
    estimatedUnitPrice: 130.0,
    createdAt: randomDate(80),
    status: 'PO Created',
    supplierShortlist: [mockSuppliers[0]],
    riskScore: 0.85,
  },
  {
    id: 'PR-006',
    number: 'PR-2024-0006',
    requester: mockEmployees[4],
    department: 'Procurement',
    material: mockMaterials[5],
    quantity: 250,
    estimatedUnitPrice: 95.0,
    createdAt: randomDate(70),
    status: 'PO Created',
    supplierShortlist: [mockSuppliers[5]],
    riskScore: 0.30,
  },
  {
    id: 'PR-007',
    number: 'PR-2024-0007',
    requester: mockEmployees[6],
    department: 'Procurement',
    material: mockMaterials[6],
    quantity: 150,
    estimatedUnitPrice: 45.0,
    createdAt: randomDate(60),
    status: 'PO Created',
    supplierShortlist: [mockSuppliers[6]],
    riskScore: 0.20,
  },
  {
    id: 'PR-008',
    number: 'PR-2024-0008',
    requester: mockEmployees[0],
    department: 'Procurement',
    material: mockMaterials[0],
    quantity: 600,
    estimatedUnitPrice: 120.0,
    createdAt: randomDate(50),
    status: 'PO Created',
    supplierShortlist: [mockSuppliers[0]],
    riskScore: 0.88,
  },
  {
    id: 'PR-009',
    number: 'PR-2024-0009',
    requester: mockEmployees[2],
    department: 'Procurement',
    material: mockMaterials[7],
    quantity: 800,
    estimatedUnitPrice: 8.5,
    createdAt: randomDate(40),
    status: 'PO Created',
    supplierShortlist: [mockSuppliers[8]],
    riskScore: 0.82,
  },
  {
    id: 'PR-010',
    number: 'PR-2024-0010',
    requester: mockEmployees[1],
    department: 'Operations',
    material: mockMaterials[4],
    quantity: 1,
    estimatedUnitPrice: 25000,
    createdAt: randomDate(30),
    status: 'PO Created',
    supplierShortlist: [mockSuppliers[7]],
    riskScore: 0.40,
  },
];

// Generate POs
export const mockPOs: PO[] = [
  {
    id: 'PO-001',
    number: 'PO-2024-0101',
    pr: mockPRs[0],
    supplier: mockSuppliers[0],
    material: mockMaterials[0],
    quantity: 500,
    unitPrice: 128.0,
    totalValue: 64000,
    createdAt: randomDate(115),
    status: 'Partially Received',
    riskScore: 0.75,
  },
  {
    id: 'PO-002',
    number: 'PO-2024-0102',
    pr: mockPRs[1],
    supplier: mockSuppliers[2],
    material: mockMaterials[1],
    quantity: 200,
    unitPrice: 88.0,
    totalValue: 17600,
    createdAt: randomDate(105),
    status: 'Closed',
    riskScore: 0.90,
  },
  {
    id: 'PO-003',
    number: 'PO-2024-0103',
    pr: mockPRs[2],
    supplier: mockSuppliers[8],
    material: mockMaterials[2],
    quantity: 1000,
    unitPrice: 13.0,
    totalValue: 13000,
    createdAt: randomDate(95),
    status: 'Closed',
    riskScore: 0.80,
  },
  {
    id: 'PO-004',
    number: 'PO-2024-0104',
    pr: mockPRs[3],
    supplier: mockSuppliers[3],
    material: mockMaterials[3],
    quantity: 1,
    unitPrice: 600,
    totalValue: 600,
    createdAt: randomDate(85),
    status: 'Closed',
    riskScore: 0.15,
  },
  {
    id: 'PO-005',
    number: 'PO-2024-0105',
    pr: mockPRs[4],
    supplier: mockSuppliers[0],
    material: mockMaterials[0],
    quantity: 300,
    unitPrice: 132.0,
    totalValue: 39600,
    createdAt: randomDate(75),
    status: 'Partially Received',
    riskScore: 0.85,
  },
  {
    id: 'PO-006',
    number: 'PO-2024-0106',
    pr: mockPRs[5],
    supplier: mockSuppliers[5],
    material: mockMaterials[5],
    quantity: 250,
    unitPrice: 97.0,
    totalValue: 24250,
    createdAt: randomDate(65),
    status: 'Closed',
    riskScore: 0.30,
  },
  {
    id: 'PO-007',
    number: 'PO-2024-0107',
    pr: mockPRs[6],
    supplier: mockSuppliers[6],
    material: mockMaterials[6],
    quantity: 150,
    unitPrice: 46.0,
    totalValue: 6900,
    createdAt: randomDate(55),
    status: 'Closed',
    riskScore: 0.20,
  },
  {
    id: 'PO-008',
    number: 'PO-2024-0108',
    pr: mockPRs[7],
    supplier: mockSuppliers[0],
    material: mockMaterials[0],
    quantity: 600,
    unitPrice: 125.0,
    totalValue: 75000,
    createdAt: randomDate(45),
    status: 'Open',
    riskScore: 0.88,
  },
  {
    id: 'PO-009',
    number: 'PO-2024-0109',
    pr: mockPRs[8],
    supplier: mockSuppliers[8],
    material: mockMaterials[7],
    quantity: 800,
    unitPrice: 9.0,
    totalValue: 7200,
    createdAt: randomDate(35),
    status: 'Closed',
    riskScore: 0.82,
  },
  {
    id: 'PO-010',
    number: 'PO-2024-0110',
    pr: mockPRs[9],
    supplier: mockSuppliers[7],
    material: mockMaterials[4],
    quantity: 1,
    unitPrice: 300,
    totalValue: 300,
    createdAt: randomDate(25),
    status: 'Closed',
    riskScore: 0.40,
  },
];

// Generate GRs
export const mockGRs: GR[] = [
  {
    id: 'GR-001',
    number: 'GR-2024-0001',
    po: mockPOs[0],
    receivedQty: 450,
    receivedAt: randomDate(100),
    discrepancyPct: 0.1,
    riskScore: 0.70,
  },
  {
    id: 'GR-002',
    number: 'GR-2024-0002',
    po: mockPOs[1],
    receivedQty: 200,
    receivedAt: randomDate(90),
    discrepancyPct: 0.0,
    riskScore: 0.90,
  },
  {
    id: 'GR-003',
    number: 'GR-2024-0003',
    po: mockPOs[2],
    receivedQty: 950,
    receivedAt: randomDate(80),
    discrepancyPct: 0.05,
    riskScore: 0.75,
  },
  {
    id: 'GR-004',
    number: 'GR-2024-0004',
    po: mockPOs[3],
    receivedQty: 1,
    receivedAt: randomDate(70),
    discrepancyPct: 0.0,
    riskScore: 0.15,
  },
  {
    id: 'GR-005',
    number: 'GR-2024-0005',
    po: mockPOs[4],
    receivedQty: 250,
    receivedAt: randomDate(60),
    discrepancyPct: 0.167,
    riskScore: 0.80,
  },
  {
    id: 'GR-006',
    number: 'GR-2024-0006',
    po: mockPOs[5],
    receivedQty: 250,
    receivedAt: randomDate(50),
    discrepancyPct: 0.0,
    riskScore: 0.30,
  },
  {
    id: 'GR-007',
    number: 'GR-2024-0007',
    po: mockPOs[6],
    receivedQty: 150,
    receivedAt: randomDate(40),
    discrepancyPct: 0.0,
    riskScore: 0.20,
  },
  {
    id: 'GR-008',
    number: 'GR-2024-0008',
    po: mockPOs[8],
    receivedQty: 780,
    receivedAt: randomDate(20),
    discrepancyPct: 0.025,
    riskScore: 0.78,
  },
  {
    id: 'GR-009',
    number: 'GR-2024-0009',
    po: mockPOs[9],
    receivedQty: 1,
    receivedAt: randomDate(10),
    discrepancyPct: 0.0,
    riskScore: 0.40,
  },
];

// Generate Invoices
export const mockInvoices: Invoice[] = [
  {
    id: 'INV-001',
    number: 'INV-2024-0091',
    supplier: mockSuppliers[0],
    po: mockPOs[0],
    gr: mockGRs[0],
    invoiceAmount: 57600,
    currency: 'INR',
    invoiceDate: randomDate(95),
    dueDate: randomDate(65),
    status: 'On Hold',
    riskScore: 0.85,
  },
  {
    id: 'INV-002',
    number: 'INV-2024-0092',
    supplier: mockSuppliers[2],
    po: mockPOs[1],
    gr: mockGRs[1],
    invoiceAmount: 18480,
    currency: 'INR',
    invoiceDate: randomDate(85),
    dueDate: randomDate(55),
    status: 'Approved',
    riskScore: 0.92,
  },
  {
    id: 'INV-003',
    number: 'INV-2024-0093',
    supplier: mockSuppliers[8],
    po: mockPOs[2],
    gr: mockGRs[2],
    invoiceAmount: 12350,
    currency: 'INR',
    invoiceDate: randomDate(75),
    dueDate: randomDate(45),
    status: 'Paid',
    riskScore: 0.75,
  },
  {
    id: 'INV-004',
    number: 'INV-2024-0094',
    supplier: mockSuppliers[3],
    po: mockPOs[3],
    gr: mockGRs[3],
    invoiceAmount: 600,
    currency: 'INR',
    invoiceDate: randomDate(65),
    dueDate: randomDate(35),
    status: 'Paid',
    riskScore: 0.15,
  },
  {
    id: 'INV-005',
    number: 'INV-2024-0095',
    supplier: mockSuppliers[0],
    po: mockPOs[4],
    gr: mockGRs[4],
    invoiceAmount: 33000,
    currency: 'INR',
    invoiceDate: randomDate(55),
    dueDate: randomDate(25),
    status: 'On Hold',
    riskScore: 0.88,
  },
  {
    id: 'INV-006',
    number: 'INV-2024-0096',
    supplier: mockSuppliers[5],
    po: mockPOs[5],
    gr: mockGRs[5],
    invoiceAmount: 24250,
    currency: 'INR',
    invoiceDate: randomDate(45),
    dueDate: randomDate(15),
    status: 'Paid',
    riskScore: 0.30,
  },
  {
    id: 'INV-007',
    number: 'INV-2024-0097',
    supplier: mockSuppliers[6],
    po: mockPOs[6],
    gr: mockGRs[6],
    invoiceAmount: 6900,
    currency: 'INR',
    invoiceDate: randomDate(35),
    dueDate: randomDate(5),
    status: 'Paid',
    riskScore: 0.20,
  },
  {
    id: 'INV-008',
    number: 'INV-2024-0098',
    supplier: mockSuppliers[8],
    po: mockPOs[8],
    gr: mockGRs[7],
    invoiceAmount: 7020,
    currency: 'INR',
    invoiceDate: randomDate(15),
    dueDate: randomDate(-5),
    status: 'Pending',
    riskScore: 0.80,
  },
  {
    id: 'INV-009',
    number: 'INV-2024-0099',
    supplier: mockSuppliers[7],
    po: mockPOs[9],
    gr: mockGRs[8],
    invoiceAmount: 300,
    currency: 'INR',
    invoiceDate: randomDate(5),
    dueDate: randomDate(-25),
    status: 'Paid',
    riskScore: 0.40,
  },
];

// Generate Fraud Alerts
export const mockFraudAlerts: FraudAlert[] = [
  {
    id: 'ALERT-001',
    entityType: 'Invoice',
    entityId: 'INV-2024-0091',
    reason: 'Invoice amount exceeds PO value by 10%. GR shows quantity shortfall.',
    severity: 'high',
    createdAt: randomDate(95),
    suggestedActions: [
      'Verify goods receipt documentation',
      'Contact supplier for clarification',
      'Review purchase order terms',
    ],
    simulationStepIndex: 3,
  },
  {
    id: 'ALERT-002',
    entityType: 'PO',
    entityId: 'PO-2024-0108',
    reason: 'Repeated high-value orders from high-risk supplier by same employee',
    severity: 'critical',
    createdAt: randomDate(45),
    suggestedActions: [
      'Review employee purchase history',
      'Verify supplier relationship',
      'Escalate to procurement manager',
    ],
    simulationStepIndex: 5,
  },
  {
    id: 'ALERT-003',
    entityType: 'Invoice',
    entityId: 'INV-2024-0092',
    reason: 'Invoice amount exceeds PO value by 5% with no GR discrepancy',
    severity: 'high',
    createdAt: randomDate(85),
    suggestedActions: [
      'Verify invoice line items',
      'Check for price adjustments',
      'Review contract terms',
    ],
    simulationStepIndex: 7,
  },
  {
    id: 'ALERT-004',
    entityType: 'GR',
    entityId: 'GR-2024-0005',
    reason: 'Significant quantity discrepancy (16.7% short) on high-value PO',
    severity: 'high',
    createdAt: randomDate(60),
    suggestedActions: [
      'Verify physical inventory',
      'Contact warehouse manager',
      'Review shipping documentation',
    ],
    simulationStepIndex: 4,
  },
  {
    id: 'ALERT-005',
    entityType: 'Supplier',
    entityId: 'SUP-001',
    reason: 'Multiple high-risk transactions with low on-time delivery rate',
    severity: 'critical',
    createdAt: randomDate(50),
    suggestedActions: [
      'Review supplier performance metrics',
      'Consider supplier audit',
      'Evaluate alternative suppliers',
    ],
    simulationStepIndex: 6,
  },
];

// Generate moderate dataset
import { generateMorePRs, generateMorePOs, generateMoreInvoices } from './generateLargeDataset';

// Expand PRs to ~60
const additionalPRs = generateMorePRs(50, mockPRs.length, mockEmployees, mockMaterials, mockSuppliers);
export const allMockPRs = [...mockPRs, ...additionalPRs];

// Expand POs to ~60
const additionalPOs = generateMorePOs(50, mockPOs.length, allMockPRs, mockSuppliers);
export const allMockPOs = [...mockPOs, ...additionalPOs];

// Expand Invoices to ~50
const additionalInvoices = generateMoreInvoices(41, mockInvoices.length, allMockPOs, mockGRs);
export const allMockInvoices = [...mockInvoices, ...additionalInvoices];

